# Generated by Django 4.0.4 on 2022-05-05 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_rename_orders_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Orders',
        ),
    ]
